spring.application.name=FPT_Cinema

spring.datasource.url=${DB_URL:jdbc:mysql://fpt-cinema-db-hgduy03-63f3.g.aivencloud.com:27667/fpt-cinema?sslMode=REQUIRED&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:avnadmin}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true